var a = 78;
var b = 78.09;
var c = "UST Global";
var d = [2,3,4,6];
var e = {ID:1,Name:'Ajay', Salary:34000.00};
var x = 67;
var y = 89;
var z = x + y;
document.write("<h2>Data types and Variables</h2>");
document.write("<ul style='font-size:20'>");
document.write("<li>Integer = "+a+"</li>");
document.write("<li>Decimal = "+b+"</li>");
document.write("<li>String = "+c+"</li>");
document.write("<li>Array = "+d+"</li>");
document.write("<li>Employee ID = "+e.ID+"</li>");
document.write("<li>Employee Name = "+e.Name+"</li>");
document.write("<li>Employee Salary = "+e.Salary+"</li>");
document.write("<li>Addition = "+z+"</li>");
document.write("</ul>");