
var a = "How are you? Where are you?";
var b = a.indexOf("you");
var c = a.lastIndexOf("you");
var d = a.search("you");
var e = a.slice(0,4);
var f = a.substring(7,10);
var g = a.substr(8,3);
var h = a.replace("you","we");
var i = a.concat("I am fine");
var j = a.charCodeAt(5);
var k = a.split(" ");
document.write("<BR><BR><BR><center><table border=1>");
document.write("<tr>");
document.write("<th><b>Method<b></th>");
document.write("<th>Main String</th>");
document.write("<th>Output</th>");
document.write("</tr>");
document.write("<tr>");
document.write("<td><b>indexOf<b></td>");
document.write("<td>"+a+"</td>");
document.write("<td>"+b+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td><b>lastindexOf<b></td>");
document.write("<td>"+a+"</td>");
document.write("<td>"+c+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td><b>Search<b></td>");
document.write("<td>"+a+"</td>");
document.write("<td>"+d+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td><b>Slice<b></td>");
document.write("<td>"+a+"</td>");
document.write("<td>"+e+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td><b>substring<b></td>");
document.write("<td>"+a+"</td>");
document.write("<td>"+f+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td><b>substr<b></td>");
document.write("<td>"+a+"</td>");
document.write("<td>"+g+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td><b>replace<b></td>");
document.write("<td>"+a+"</td>");
document.write("<td>"+h+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td><b>concat<b></td>");
document.write("<td>"+a+"</td>");
document.write("<td>"+i+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td><b>charCodeAt<b></td>");
document.write("<td>"+a+"</td>");
document.write("<td>"+j+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td><b>split<b></td>");
document.write("<td>"+a+"</td>");
document.write("<td>"+k[0]+"</td>");
document.write("</tr>");
document.write("</table></center>");


